# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/:categories/:title

# Setup
title:            test
tagline:          'blog'
description:      'My personal blog.'
url:              http://fahimazulfath.github.io/test/
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Fahima Zulfath
  url:            https://google.com/IanCamporezBrunelli

paginate:         5

# Custom vars
cover:            /assets/images/cover.jpg


menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Camporez
  url:            http://fahimazulath.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
